server:
  port: 8080
logging:
  config: classpath:log/logback-dev.xml
spring:
  mvc:
    throw-exception-if-no-handler-found: true # 出现错误时, 直接抛出异常
  resources:
      add-mappings: false #不要为我们工程中的资源文件建立映射
wx:
  mp:
   configs:
      appId: wx931dc158ca3849d0 #（一个公众号的appid）
      secret: e6064defa8df7e1b4f951bccfee48497 #（公众号的appsecret）
      token: 111 #（接口配置里的Token值）
      aesKey: 111 #（接口配置里的EncodingAESKey值）